---
- name: Apply Kubernetes manifests using Ansible roles
  hosts: localhost
  remote_user: parag-piprewar
  become: false
  vars:
    kubeconfig_path: "{{ lookup('env', 'KUBECONFIG') | default('/home/parag-piprewar/.kube/config', true) }}"

  roles:
    - role: envSetup_role
    - role: patient_role
    - role: doctor_role
    - role: appointment_role
    - role: notification_role
    - role: monitoring_role
    # - role: elk_role # Commented out to save memory (removes ELK and Filebeat)
    - role: vault_role
    - role: billing_role
    - role: ai_diagnostics_role
    - role: frontend_role
